console.clear();
var teclado = require('prompt-sync')();
var n1 = parseFloat(teclado("Digite o primeiro n\u00FAmero"));
var n2 = parseFloat(teclado("Digite o segundo n\u00FAmero"));
var n3 = parseFloat(teclado("Digite o terceiro n\u00FAmero"));
var n4 = parseFloat(teclado("Digite o quarto n\u00FAmero"));
var n5 = parseFloat(teclado("Digite o quinto n\u00FAmero"));
var n6 = parseFloat(teclado("Digite o sexto n\u00FAmero"));
var n7 = parseFloat(teclado("Digite o s\u00E9timo n\u00FAmero"));
var n8 = parseFloat(teclado("Digite o oitavo n\u00FAmero"));
var n9 = parseFloat(teclado("Digite o nono n\u00FAmero"));
var n10 = parseFloat(teclado("Digite o d\u00E9cimo n\u00FAmero"));
console.clear();
console.log("A m\u00E9dia \u00E9 " + (n1 + n2 + n3 + n4 + n5 + n6 + n7 + n8 + n9 + n10) / 10);
